### ISSUE TITLE
Typo on Package Creation Guide pt. 2

### ISSUE THREAD

**Issue by arvganesh** [tlienart/tlienart.github.io#37]
I was going through [this guide ](https://tlienart.github.io/pub/julia/dev-pkg2.html) and found a typo. Under [this](https://tlienart.github.io/pub/julia/dev-pkg2.html#script_for_travis) heading, `.appveyor.yml` should be `.travis.yml`.

**Comment by tlienart** [comment]
oh wow, thanks for that 😄 I really, really need to update that website

**Comment by arvganesh** [comment]
No problem!
