### ISSUE TITLE
How can I apply the zig-zag process to a time series? It has been difficult for me because there is little information

### ISSUE THREAD

**Issue by chcolapara** [tlienart/tlienart.github.io#43]
How can I apply the zig-zag process to a time series? It has been difficult for me because there is little information

**Comment by tlienart** [comment]
@chcolapara I archived the other repo because I haven't worked on the PDSampler for years; if you would like to ask questions about the ZigZag you can try asking to this package: https://github.com/mschauer/ZigZagBoomerang.jl
